# Generated by Django 4.1.3 on 2022-11-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rules', models.TextField()),
                ('image', models.ImageField(upload_to='sport_images')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('venue', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
