# Generated by Django 4.1.3 on 2022-11-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sport_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sport_images'),
        ),
    ]
