# Generated by Django 4.1.3 on 2022-11-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sport_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='sport_images'),
        ),
    ]
