# Generated by Django 4.1.3 on 2022-11-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_sport_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='maximumPlayers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='minimumPlayers',
            field=models.IntegerField(null=True),
        ),
    ]
