# Generated by Django 4.1.3 on 2022-11-30 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('team_type', models.CharField(choices=[('Engineering', 'Engineering'), ('Open', 'Open')], max_length=200)),
                ('institute_name', models.CharField(max_length=200)),
                ('logo', models.FileField(blank=True, null=True, upload_to='team_images')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('sport_incharge_name', models.CharField(max_length=200)),
                ('sport_incharge_number', models.CharField(max_length=200)),
                ('sport_incharge_email_id', models.CharField(max_length=200)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=200)),
                ('college_id', models.FileField(blank=True, null=True, upload_to='college_id')),
                ('aadhar_card_number', models.CharField(max_length=200)),
                ('team', models.ManyToManyField(related_name='players', to='api.team')),
            ],
        ),
    ]
