# Generated by Django 4.1.3 on 2022-11-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_team_player_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain_name',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
