# Generated by Django 4.1.3 on 2022-11-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_team_captain_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='aadhar_card_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, related_name='players', to='api.team'),
        ),
    ]
