# Generated by Django 4.1.3 on 2022-12-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_player_aadhar_card_number_alter_player_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='aadhar_card_number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='college_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_type',
        ),
        migrations.AddField(
            model_name='team',
            name='need_accomodation',
            field=models.BooleanField(default=False),
        ),
    ]
