# Generated by Django 4.1.3 on 2022-12-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_player_aadhar_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
