# Generated by Django 4.1.3 on 2023-01-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_player_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='maximumPlayers',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='minimumPlayers',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='price',
        ),
        migrations.AddField(
            model_name='sport',
            name='maximumPlayersFemale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='maximumPlayersMale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='minimumPlayersFemale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='minimumPlayersMale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='priceFemale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='priceMale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
