# Generated by Django 4.1.3 on 2023-01-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_sport_maximumplayers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
