# Generated by Django 4.1.3 on 2023-01-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_team_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_male_team',
            field=models.BooleanField(default=True),
        ),
    ]
