# Generated by Django 4.1.3 on 2023-01-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_team_is_male_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='accomodation_preference',
            field=models.CharField(default='', max_length=50),
        ),
    ]
