# Generated by Django 4.1.3 on 2023-01-29 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_contact_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_ref_no', models.CharField(blank=True, max_length=20, null=True)),
                ('order_status', models.CharField(blank=True, max_length=20, null=True)),
                ('faliure_message', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('card_name', models.CharField(blank=True, max_length=20, null=True)),
                ('status_code', models.CharField(blank=True, max_length=10, null=True)),
                ('status_message', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.CharField(blank=True, max_length=20, null=True)),
                ('trans_date', models.DateTimeField(blank=True, null=True)),
                ('billing_name', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('billing_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='is_payment_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.payment'),
        ),
    ]
