# Generated by Django 4.1.3 on 2023-01-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_payment_team_is_payment_successful_team_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='faliure_message',
            new_name='failure_message',
        ),
    ]
