# Generated by Django 4.1.3 on 2023-02-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_faliure_message_payment_failure_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
