# Generated by Django 4.1.3 on 2023-02-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_contact_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='need_meal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='need_transport',
            field=models.BooleanField(default=False),
        ),
    ]
