# Generated by Django 4.1.3 on 2023-02-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_team_need_meal_team_need_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='accomodation_preference',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain_name',
            field=models.CharField(blank=True, default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport_incharge_email_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport_incharge_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport_incharge_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
