# Generated by Django 4.1.3 on 2023-02-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_team_accomodation_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='institution_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
